### ISSUE TITLE
Add server authentication w/ Firebase

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/simplicity2#19]
Authentication should be done as express middleware in the server. If the post request has a FireBase token, then we use it to verify and get user information to add to the request.

* https://firebase.google.com/docs/auth/server/
* https://firebase.google.com/docs/auth/server/verify-id-tokens

And this generally on GraphQL and authentication (more on google):

* https://medium.com/the-graphqlhub/graphql-and-authentication-b73aed34bbeb#.drdbyucas

**Comment by carlyleec** [comment]
So I've been thinking about authentication in SimpliCity and using GraphQL, and our tiers of servers and private and public data, and....

I think that we might be over complicating things in regards to the use of multiple ArcGIS for Server instances for private (internal) and public data in SimpliCity. If we're going to build a GraphQL server, we're essentially going to build an API. Why not just query the database in the resolvers? If we already had the ArcGIS for Servers set up in the configuration we want, we could just plug in the REST endpoints, but we don't. We still have to build those servers. The majority of "private" data will be non-spatial anyways, BUT we do have the awesome power of PostGIS to do spatial queries if needed (no ArcGIS required).

To the point: I think we should just use GraphQL with direct database queries as resolvers for internal "private" data instead of using the ArcGIS for Server. That way we can handle **ALL** of our authentication on the GraphQL server with Firebase JWTs which will get us the user's email. Then, we can use something like this, [Google Groups Settings API](https://developers.google.com/admin-sdk/groups-settings/v1/reference/) to retrieve the user's groups, which will define their roles???? Is that really how we're going to do that??? Nevertheless, with Firebase we'll get their **identity**, and with their email we can determine their **authorization** ...somehow. 

We can still publish public data to ArcGIS for Server for mapping and the Open Data Portal. And, yes, we'll still need an internal ArcGIS for Server instance for water data, etc. But I think we might be forcing the issue a bit with the ArcGIS REST API. 

One last thing, I'm not saying that we should only do GraphQL internally. I think we should do it for both internal and external (private and public), but that it should be the only option for internal data.

**Comment by ejaxon** [comment]
I think this makes sense, but I'd like to talk through the scenarios. We should also connect today with Tom or whoever has been thinking about roles and permissions using Google  apps and understand how those are supposed to work so that we can do the research on our end.

**Comment by ejaxon** [comment]
Note that Firebase authentication token is now available in all resolvers, but what we really need to do is actually accomplish the authentication in the middleware.
